### ISSUE TITLE
Idea: Graph-based user recommendation

### ISSUE THREAD

**Issue by DonaldTsang** [Akaisorani/pixiv-crawler#3]
If I were to give you 300 artists of similar themes, is it possible to find other related artists that produces such themes (assume that we are going 3 levels deep, that means A liking B liking C liking D means all of them are related)?

**Comment by Akaisorani** [comment]
It is interesting to see this question under a image spider repository. This problem is seems been studied for a long time in the area of recommendation system and social network.
For finding other similar artists, you can refer to Collaborative Filtering algorithm.
For calculating the similarity of two artists, may be you can refer to SimRank [\[1\]](https://dl.acm.org/citation.cfm?id=775126) [\[2\]](https://arxiv.org/abs/1512.02714).
For clustering similar artists, you can refer to those clustering algorithms (e.g. kNN) on graph.
Graph embedding may help, you can refer to GNN, GCN...
To do this things on image level, you can refer to techneques in the area of computer vision.

**Comment by DonaldTsang** [comment]
Here are some CF algorithms written in other languages:
- https://github.com/guoguibing/librec
- https://github.com/zhenghaoz/gorse

but I would like to see some in Python as well like https://github.com/benfred/implicit 

Some basic principles though: do not use neural networks or computer vision since it is computationally intensive
The goal would would be to scrape a set of artists' "collections" for preferences, build a preference network,
and then use their preferences for CF similar artists with the same themes or properties (if community detection is possible).
Currently we are dealing with only finding artists that are well loved by other artists, niche artists would come later.

And I would like to put some co-references here:
- https://github.com/bebound/pixiv
- https://github.com/chenjiandongx/pixiv
- https://github.com/tsubasa/pixiv.py
